### ISSUE TITLE
[PE-D] Phone numbers with less than 9 digits are allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W12-4/tp#163]
![image.png](https://raw.githubusercontent.com/myc37/ped/main/files/20eb9e40-2512-429e-88b4-f12727297d86.png)

- You may or may not consider this a bug, which is why I have indicated low severity
- This is a feature inherited from AB3 which only requires 3 digits for phone number, but phone numbers in Singapore have exactly 8 digits
- I suggest following the local phone number format for better accuracy

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: myc37/ped#3

**Comment by ckcherry23** [comment]
This is intentional because we are not limiting to only Singaporean numbers and it is possible for certain numbers to only have 3 digits for emergency numbers.
