### ISSUE TITLE
[PE-D] Navigation between detailed content of a person and person list

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#171]
After adding/editing a person, I need to manually press 'back' to go back to the person list, which it quite troublesome.
Refers to 4th point of Feature Flaws on the module website: "Features that are not optimized enough for fast-typists or target users."

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jacky142857/ped#2

**Comment by muraddurrani** [comment]
Intentional design choice due to the volume of information displayed for each contact.
