### ISSUE TITLE
[PE-D] Cannot edit a person when viewing the contact list

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#173]
When editing a person, I have to type 'view INDEX' to go to that person first then edit, which is quite time consuming and troublesome. This is against 4th point of Feature Flaws on the module website: "Features that are not optimized enough for fast-typists or target users."

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jacky142857/ped#3

**Comment by muraddurrani** [comment]
Intentional design choice due to the volume of information stored for a person.
