### ISSUE TITLE
[PE-D] Typo in command table

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#182]
![image.png](https://raw.githubusercontent.com/takufunkai/ped/main/files/e7e1f9d4-2604-426a-8270-68969e95723d.png)

Section 4, create meeting

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: takufunkai/ped#4

**Comment by NicsunXnus** [comment]
I will do this in my PR for #202 since it coincides with this
