### ISSUE TITLE
[PE-D] Email address validity

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#189]
![image.png](https://raw.githubusercontent.com/myc37/ped/main/files/96943b6e-ea2f-43bd-8f8b-300075af95d1.png)

- This is a feature flaw inherited from AB3
- Email addresses without the ".com" behind are invalid, so your application should ideally check for that as well beyond just checking for the "@" domain.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: myc37/ped#9

**Comment by muraddurrani** [comment]
Not a bug
