### ISSUE TITLE
[PE-D] Able to add duplicate contacts with case-sensitive names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W12-4/tp#195]
May be confusing to a user who mistakenly creates a non-capitalised contact.

![image.png](https://raw.githubusercontent.com/petermonky/ped/main/files/eff5cd7b-c2d5-473a-9bea-58c2f6503b18.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: petermonky/ped#9

**Comment by ckcherry23** [comment]
- Case insensitive check in Reache
- Update DG that name and tags cannot be the same
