### ISSUE TITLE
[PE-D] Error in creating new meeting (non-existent participant)

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#196]
![image.png](https://raw.githubusercontent.com/takufunkai/ped/main/files/0394e017-ebe3-4add-bc45-27d8d871ba7e.png)

When running the command to create a new meeting with a participant index that doesn't exist, we receive 2 conflicting replies:
`Unknown contact: 2`
`Created a new meeting:...`

When it should realistically just fail and send an error message.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: takufunkai/ped#9

**Comment by ckcherry23** [comment]
Duplicate of #164
