### ISSUE TITLE
User guide formatting

### ISSUE THREAD

**Issue by ckcherry23** [AY2122S2-CS2103T-W12-4/tp#24]
2.3.1 Symbols legend formatting needs to be fixed

**Comment by NicsunXnus** [comment]
How so?

> 2.3.1 Symbols legend formatting needs to be fixed

**Comment by ckcherry23** [comment]
I don't think the website has the expected formatting:
<img width="790" alt="Screenshot 2022-03-04 at 1 37 13 PM" src="https://user-images.githubusercontent.com/68203159/156705979-67be8efd-33d7-4449-ac23-562772716e4d.png">

This is our Google docs user guide:
<img width="657" alt="Screenshot 2022-03-04 at 1 38 08 PM" src="https://user-images.githubusercontent.com/68203159/156706066-f43c4b8b-6fba-4528-82cb-25ab3a89755e.png">

**Comment by ckcherry23** [comment]
Can you confirm if you have this issue as well on the website?

**Comment by NicsunXnus** [comment]
![looks like this4](https://user-images.githubusercontent.com/77189033/156707943-9118ec48-1060-4833-9fdf-5acc44c1c44c.png)

It looks like this on my end. I am not sure what can fix your problem. Maybe others will know?

**Comment by ckcherry23** [comment]
Is this the website or the GitHub rich diff?
The screenshot I attached was from the website, which is supposed to be the same across all platforms right?

**Comment by NicsunXnus** [comment]
Sorry, I didn't realise you mentioned the website. Can you link to the website, I am not where to look for it.

**Comment by ckcherry23** [comment]
https://ay2122s2-cs2103t-w12-4.github.io/tp/UserGuide.html#23-editing-information

**Comment by NicsunXnus** [comment]
Ok fixed it! Can you check on your end?

**Comment by ckcherry23** [comment]
<img width="792" alt="Screenshot 2022-03-04 at 2 34 17 PM" src="https://user-images.githubusercontent.com/68203159/156712102-b22e8e37-cd2e-4485-8428-5b68789674f4.png">

The table is fixed, thanks!
There is still a minor issue of <p> though

**Comment by NicsunXnus** [comment]
Alright, fixed it.
