### ISSUE TITLE
As a busy user, I want to store my meetings

### ISSUE THREAD

**Issue by tonishka** [AY2122S2-CS2103T-W12-4/tp#88]
so that I can view and organise them effectively.

**Comment by NicsunXnus** [comment]
1) A person can have 0..* meetings
2) A person cannot create a meeting with an attendee that is not found in the storage

**Comment by ckcherry23** [comment]
Notes for 3)
I think we can use:
- `meet`: analogous to 'add'
- `update`: analogous to 'edit'
-  `cancel`: analogous to 'delete''

to avoid the `-m` delimiter and continue with a parsing implementation similar to what we have now.
